docs(recipe): update urql example to fit on latest version
enisdenjo/graphql-ws pull request #471
Opened 2023-04-18 11:04 UTC by spacebarley

Hi, I updated the example for using `urql`, because the current example is not valid for the latest `urql` package.

* move `import { defaultExchanges }` to `import { cacheExchange, fetchExchange }`
  * `defaultExchanges` are removed in the latest package. ([CHANGELOG link](https://github.com/urql-graphql/urql/blob/35657e771633be43b850f0a1f7fdbac94b075dd7/packages/core/CHANGELOG.md#major-changes))

* Type assertion for client.subscribe
  * The argument for `forwardSubscription` returned non-nullable string `query` in previous packages, ([related link](https://github.com/urql-graphql/urql/blob/%40urql/vue%401.0.4/packages/core/src/exchanges/subscription.ts))
  * But it does return a nullable `query` now. ([related link #1](https://github.com/urql-graphql/urql/blob/main/packages/core/src/exchanges/subscription.ts#L68), [related link #2](https://github.com/urql-graphql/urql/blob/main/packages/core/src/internal/fetchOptions.ts#L11))

  * So it have to be asserted as a non-nullable value before using it in `graphql-ws`.

Any better changes/comments are welcomed. (I am quite a newbie for this package)

Thanks,
spacebarley

2023-04-18 21:42 UTC, enisdenjo requested changes
Please fix the linting issues first.

2023-04-19 05:49 UTC, spacebarley commented
I ran `prettier --write` in my local. Thanks.

2023-04-19 10:04 UTC, enisdenjo approved these changes
Cheers!

2023-04-19 10:04 UTC, merged

2023-05-12 11:31 UTC, enisdenjo commented
:tada: This PR is included in version 5.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/graphql-ws/v/5.13.0)
- [GitHub release](https://github.com/enisdenjo/graphql-ws/releases/tag/v5.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: