feat: log warning in dev when using incorrect protocol
enisdenjo/graphql-ws pull request #92
Opened 2021-01-06 20:41 UTC by vegetabill

I was integrating graphql-ws for a hackathon at work and it took me ages to figure out that the problem was I was trying to test with [Altair](https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja), a nice GraphiQL-like extension that looked like it supported extensions, but uses the ``

Adding a warning in dev mode to help folks like me figure out this faster since the ecosystem is a bit messy for a new person.

### Example Screenshot

![](https://drive.google.com/uc?id=1VADlTcAoXaio2YPXTKBCNg9nvV59If5t)

Thanks for considering it.

2021-01-11 09:40 UTC, enisdenjo requested changes
One thing that I'd recommend in addition is not even allowing the WS upgrade in case the subprotocol is wrong. You can use the `Sec-WebSocket-Protocol` header to validate the request. [This recipe might help you out.](https://github.com/enisdenjo/graphql-ws#ws-backwards-compat)

Nevertheless, since the lib checks it too - it makes sense to have this helpful warning.

2021-01-11 09:40 UTC, enisdenjo commented on src/server.ts
> +        );
No need to have this `logDeveloperWarning`. I try avoiding any logs and rely on exposing as much as possible for the users. Simply put the `if != PROD console.warn` right here.

Also, the indentation in backticks will be preserved. Consider inlining the message.

2021-01-13 00:03 UTC, closed without merging

2021-01-13 00:24 UTC, enisdenjo commented
:tada: This issue has been resolved in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/graphql-ws/v/4.0.0)
- [GitHub release](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-01-13 01:44 UTC, vegetabill commented
Awesome thanks!